config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  unauthenticated do
    root "home#index" , as: :unauthenticated_root
  end


  authenticated :user do
    root 'articles#index', as: :authenticated_root
  end

  devise_scope :user do
    get :logout, to: "devise/sessions#destroy"
  end


  resources :articles 
  resources :comments


  
  resources  :home, only: [:index, :show]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
 
  
end
  

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  mount_uploader :image, ImageUploader
  
  extend FriendlyId
  friendly_id :title, use: :slugged

  include PgSearch::Model

  pg_search_scope :search_by_article, against: [:title, :text]
  
  pg_search_scope :search_by_category, associated_against: { 
    category: :title
  }

  def self.search_by_category(id)
    where(category_id: id)
  end

  def user_email
    user.email if user
  end
  

  paginates_per 25

  has_many :taggings, as: :taggable
  has_many :tags, through: :taggings, class_name: 'Gutentag::Tag'

  belongs_to :category
  
  validates :title, presence: true, length: { in: 6..50}, uniqueness: { case_sensitive: false }
  validates :text, presence: true, length: { in: 10..10000, too_long: "%{count} characters maximum allowed"}
  
  has_rich_text :text

  has_many :comments, dependent: :destroy


  



  Gutentag::ActiveRecord.call self
  
  def tags_as_string
    tag_names.join(", ")
  end

  def tags_as_string=(string)
    self.tag_names = string.split(/,\s*/)
  end

  
end

   
  

app/models/category.rb
class Category < ApplicationRecord
    has_many :articles


    #validates  :articles, presence: true, :length => { :minimum => 1 }
    include PgSearch::Model

    pg_search_scope :search_by_category, against: :category_title
  
    validates :title, presence: true, length: { in: 6..50}, uniqueness: { case_sensitive: false }

    def category_title
        title
         
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :trackable

         
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:edit, :update, :destroy, :show]
  before_action :authenticate_user!
 

  # GET /articles or /articles.json
  def index
  @articles = Article.order(:title).page(params[:page])

  # Apply filters
  @articles = @articles.search_by_article(params[:search]) if params[:search].present?
  @articles = @articles.tagged_with(params[:tag]) if params[:tag].present?
  @articles = @articles.search_by_category(params[:category]) if params[:category].present?

  # Load all categories and prepend the "All categories" option
  @categories = Category.all.map { |category| [category.title, category.id] }
  @categories.prepend(["All categories", ""])
end



  # GET /articles/1 or /articles/1.json
  def show
    # @article = Article.new(article_params)
    
      @user = User.find(@article.user_id)
      @comments = @article.comments
      @comment = Comment.new
      @comment.article_id = @article.id
      add_breadcrumb "Back to articles", :articles_path, class: "link-dark"

  end

  # GET /articles/new
  def new
    @article = Article.new
    add_breadcrumb "Back to articles", :articles_path, class: "link-dark"
  end

  # GET /articles/1/edit
  def edit
    
  end

  # POST /articles or /articles.json
  # def create
  #   article = Article.create! 
  #   params.require(:article).permit(:title, :content)
  #   redirect_to article
  # end

  #  debugger
def create
  @article = Article.new(article_params)
  # @article.picture.attach(params[:article][:picture])
  # @article.user_id = @user.id
  # @article.image.attach(params[:article][:image])
  # uploader = imageUploader.new
  # uploader.store!(my_file)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    # @article = Article.destroy(params[:id])
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])  
    end


    def article_params
      params.fetch(:article, {})
      params.require(:article).permit(:title, :text, :search, :category_id, :image, :tags_as_string)
            .merge(user: current_user)
    end
    
 
    
  end

 

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    # before_action :set_comment

    
    def create
        @article = Article.friendly.find(params[:comment][:article_id])
        puts " ARTICLOSAFDsdfsdlvkjhsdiofsdiofsd #{@article}"
        @comment = Comment.new(comment_params)
        @comment.article  =  @article
        @comment.user = current_user
        
        if @comment.save!   
            redirect_to article_path(@article)
        else
            flash[:notice] = "Error saving comment!"
            redirect_to article_path(@article)
       
        end
    end

    private

    def set_comment
        # @comment = @article.comments.find(params[:id])
      end
  

  
    def comment_params
      params.require(:comment).permit(:body, :user, :article_id)
          
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :set_article, only: %i[ show  ]
  # before_action :authenticate_user!


  # GET /articles or /articles.json
  def index
    @articles = Article.order(:title).page(params[:page])

    @articles = @articles.search_by_article(params[:search]) if params[:search].present?
    
    @articles = @articles.tagged_with(params[:tag]) if params[:tag]

    @articles = @articles.search_by_category(params[:category]) if params[:category].present?
    
    # @articles = @articles.search_by_category_id(params[:category_id])

    @categories = Category.all.map { |category| [category.title, category.id] }
    @categories.prepend(["All categories", ""])

    #@categories = Category.search_by_category(params[:search  ]) if params[:search].present?

    # @tag = Tag.all
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article = Article.friendly.find(params[:id])
    @user = User.find(@article.user_id)
    @comments = @article.comments
    @comment = Comment.new
    @comment.article_id = @article.id
    add_breadcrumb "Back to articles", :articles_path, class: "link-dark"
  end

end

 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.slim
<div id="<%= dom_id article %>">

  = simple_form_for @article do |f|
        - if @article.errors.any?
            #error_explanation
                h2 
                    = pluralize(@article.errors.count, "error") 
                    | prohibited this article from being saved：
                ul
                    - @article.errors.full_messages.each do |message|
                        li= message
        
                
    
        div.mb-3
            = f.label :article ,class:"me-2"
            = @article.user_email
       
        div
            = f.input :title, require: true
                
            = f.label :text
            = f.rich_text_area :text,  style: "width: 650px"
        div
     
            = f.input :image
         
        div            
            = f.association :category, required: true, label_method: :category_title, value_method: :id
                        

        div            
            = f.label :tag, require: true, value: "Tags", class: "form-label"
            = f.text_field :tags_as_string, id: :product_tags_as_string, class: "form-control"  
 
       
       
        div.form-actions.mt-3.d-flex.justify-content-center       
            = f.submit class: "btn btn-dark"
                            

    
</div>

app/views/articles/edit.html.slim
div.d-flex.flex-wrap.justify-content-center
    div.h3.mt-3.mb-5.d-flex.justify-content-center
        | Editing article
    div.input-group.mb-3           
    = render "article", article: @article 
    
                        
                  
                    

app/views/articles/index.html.slim
div.container.column
    div.d-flex.justify-content-between.me-2.ms-2.mt-4
        = form_tag(articles_path, style: "width: 70%",  method: :get, class: "d-flex input-group") do
            = text_field_tag(:search, params[:search], class: "form-control string requred ", placeholder: "Search for the article ... ")
                        
            = button_tag("🔍", class: "input-group-text")
                
        = form_tag(articles_path, method: :get) do
            = select_tag "category", options_for_select(@categories,selected: params[:category]), onchange: 'this.form.submit()', class: "btn btn-outline-dark dropdown-toggle"
        
        = link_to "New article", new_article_path, class: "btn btn-dark"


    div.d-flex.justify-content-start.mt-5.ms-2
        h4
            | All Articles

    <p style="color: green" id="notice">
        = notice
    .article-container.d-flex.align-items-center.flex-wrap.justify-content-evenly 
        - @articles.each do |article| 
            div.card.m-2 style="width: 400px; min-height: 200px" 
                div.card-body
                    h4.card-title.p-1
                            = link_to article.title, article, :title => article.title, class: "link-dark"
                    h6.card-subtitle 
                        = article.category.title
                    card-text
                        = article.text
                    div.badge.text-bg-dark.p-1
                        = article.tags_as_string
                    .d-flex.flex-row.grid.gap-2.pt-3
                        div 
                            = link_to 'Edit', edit_article_path(article),class: "link-dark"
                        div 
                            | /
                        div
                            = link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?'},class: "link-dark"

                     


div.d-flex.justify-content-end
    = paginate @articles 

app/views/articles/new.html.slim
div.d-flex.flex-wrap.justify-content-center
    = simple_form_for @article do |f|
        div.h3.mt-3.mb-5.d-flex.justify-content-center
            | Create your perfect Article!
        div.input-group.mb-3           
            = render "article", article: @article 
            
                        
                                
                        
                                
                            

app/views/articles/search.html.slim
@articles.each do |article| 
  h2
    = link_to article.title, article 
     p
        = article.body 
         article.tags.each do |tag| 
        = link_to tag.name, tag_path(tag) 

               

app/views/articles/show.html.slim
.d-flex.flex-column.justify-content-evenly
            .d-flex.flex-row.justify-content-evenly
                .d-flex.flex-column.w-50
                    <p style="color: green" id="notice">
                        = notice  
                           
                    .d-flex.flex-column.grid.gap-3
                        h1
                            =@article.title
                        
                        div   
                            strong Tags:
                            |  
                            =@article.tags_as_string

                        div
                            strong Text:
                            =@article.text
                        div
                            strong Author:
                            | 
                            = current_user.email if user_signed_in?

                        div
                            
                            =render "comments/show" , article: @article 

                            =render "comments/comment" , article: @article 


                            

                div.mt-4
                    - if @article.image?
                        = image_tag @article.image.thumb.url 
                    - else
                        | No photo available
                         


.d-flex.flex-row.grid.gap-2.justify-content-center.mt-5

        = link_to 'Edit', edit_article_path(@article), class: "btn btn-dark"

        = button_to 'Delete', @article, :method => :delete, class: "btn btn-outline-dark"

app/views/comments/_comment.html.slim
= simple_form_for [@comment] do |f|
    strong 
        | Add comment
    .d-flex.flex-row
        = f.text_field :body, class: "form-control"
        = f.submit "Reply" , class: "btn btn-dark"
        = f.hidden_field :article_id, :value => @article.slug



/ = form_with model: [ @article.comments.build] do |f|
/     strong 
/         | Add comment
/     div.d-flex.flex-row
/         = f.text_field :body, class: "form-control"
/         = f.submit "Reply" , class: "btn btn-dark"
/         = f.hidden_field :article_id, :value => @article.id

app/views/comments/_show.html.slim
strong
    | Comments:
    =@article.comments.size
- if @article.comments.try(:any?)
  - @article.comments.each do |comment|
    div.d-flex.flex-column.m-2
        div
            = comment.body
        small
            = comment.user.email
        = link_to "Destroy this comment", article_path(@article, comment), method: :delete, class: "link-dark", form: { data: { turbo_confirm: "Are you sure?" } }
- else
  div
    | No comments found.

app/views/home/index.html.slim
div.container.column
    div.d-flex.justify-content-between.me-2.ms-2.mt-4
        = form_tag(articles_path, style: "width: 70%",  method: :get, class: "d-flex input-group") do
            = text_field_tag(:search, params[:search], class: "form-control string requred ", placeholder: "Search for the article ... ")
                        
            = button_tag("🔍", class: "input-group-text")
                
        = form_tag(articles_path, method: :get) do
            = select_tag "category", options_for_select(@categories,selected: params[:category]), onchange: 'this.form.submit()', class: "btn btn-outline-dark dropdown-toggle"
        
        = link_to "New article", new_article_path, class: "btn btn-dark"


    div.d-flex.justify-content-start.mt-5.ms-2
        h4
            | All Articles

    <p style="color: green" id="notice">
        = notice
    .article-container.d-flex.align-items-center.flex-wrap.justify-content-evenly 
        - @articles.each do |article| 
            div.card.m-2 style="width: 400px; min-height: 200px" 
                div.card-body
                    h4.card-title.p-1
                            = link_to article.title, article, :title => article.title, class: "link-dark"
                    h6.card-subtitle 
                        = article.category.title
                    card-text
                        = article.text
                    div.badge.text-bg-dark.p-1
                        = article.tags_as_string

div.d-flex.justify-content-end
    = paginate @articles 

app/views/home/show.html.slim
   .d-flex.flex-column.justify-content-evenly
            .d-flex.flex-row.justify-content-evenly
                .d-flex.flex-column.w-50
                    <p style="color: green" id="notice">
                        = notice  
                           
                    .d-flex.flex-column.grid.gap-3
                        h1
                            =@article.title
                        
                        div   
                            strong Tags:
                            |  
                            =@article.tags_as_string

                        div
                            strong Text:
                            =@article.text
                        div
                            strong Author:
                            | 
                            = current_user.email if user_signed_in?

                        div
                            
                            =render "comments/show" , article: @article 

                            =render "comments/comment" , article: @article 


                            

            div.mt-4
                   
                = image_tag(@article.image_url(:thumb)) if @article.image.present?
                   

.d-flex.flex-row.grid.gap-2.justify-content-center.mt-5

        = link_to 'Edit', edit_article_path(@article), class: "btn btn-dark"

        = button_to 'Delete', @article, :method => :delete, class: "btn btn-outline-dark"

app/views/layouts/_nav.html.slim
div.navbar.navbar-expand.bg-body-tertiary
    div.container-fluid.ps-5.pe-4
        h2 
            = link_to "Article", new_article_path, class: "link-dark"
        div.d-flex.gap-2
            -if user_signed_in?
                = link_to "Profile", edit_user_registration_path, class: "btn btn-outline-dark"
                = link_to "Logout", logout_path, class: "btn btn-dark"
            - else
                = link_to "Sign in", new_user_registration_path, class: "btn btn-outline-dark"
                = link_to "Login", new_user_session_path, class: "btn btn-dark"

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>BlogOfVito</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "actiontext" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"
    rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
   
  </head>

  <body>
    <%= render partial: "layouts/nav"%>
    <div class = "container">
      
      <%= yield %>
      <%= render_breadcrumbs :separator => ' / ' %>
     
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>